spring.datasource.url=jdbc:mysql://springboot-bhandariakash627-8c5d.d.aivencloud.com:21030/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_M0p2FkP2J3x58Yo70j_
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update